//! `KeychainProvider` impl backed by the `keyring` crate (system keychain
//! on macOS / Windows / Linux Secret Service).

use async_trait::async_trait;
use keyring::Entry;
use swarm_p2p_core::libp2p::identity::Keypair;
use swarmnote_core::{AppError, AppResult, KeychainProvider};
use tracing::{info, warn};

const SERVICE: &str = "com.swarmnote";
const KEYPAIR_KEY: &str = "ed25519-keypair";

/// Desktop keychain adapter. Calls into the OS keychain via the `keyring`
/// crate; falls back to an ephemeral in-memory keypair if the keychain is
/// unavailable (e.g. headless Linux without Secret Service).
pub struct DesktopKeychain;

impl DesktopKeychain {
    pub fn new() -> Self {
        Self
    }
}

impl Default for DesktopKeychain {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl KeychainProvider for DesktopKeychain {
    async fn get_or_create_keypair(&self) -> AppResult<Vec<u8>> {
        // `keyring` is a blocking API — run it on the blocking pool so we
        // don't stall the executor.
        tokio::task::spawn_blocking(load_or_generate_keypair_bytes)
            .await
            .map_err(|e| AppError::KeychainUnavailable(format!("join error: {e}")))?
    }
}

/// Synchronous load-or-generate. Returns the protobuf-encoded keypair bytes.
fn load_or_generate_keypair_bytes() -> AppResult<Vec<u8>> {
    match load_from_keychain() {
        Ok(Some(bytes)) => {
            info!("Loaded existing keypair from system keychain");
            Ok(bytes)
        }
        Ok(None) => {
            info!("No existing keypair found, generating new Ed25519 keypair");
            let keypair = Keypair::generate_ed25519();
            let bytes = keypair
                .to_protobuf_encoding()
                .map_err(|e| AppError::KeychainUnavailable(format!("encode: {e}")))?;
            save_to_keychain(&bytes)?;
            info!("New keypair saved to system keychain");
            Ok(bytes)
        }
        Err(e) => {
            warn!("System keychain unavailable: {e}, generating ephemeral keypair");
            // Ephemeral fallback: returns generated bytes but does NOT persist
            // — every launch produces a new PeerId until the keychain works.
            let keypair = Keypair::generate_ed25519();
            keypair
                .to_protobuf_encoding()
                .map_err(|e| AppError::KeychainUnavailable(format!("encode: {e}")))
        }
    }
}

fn load_from_keychain() -> AppResult<Option<Vec<u8>>> {
    let entry = Entry::new(SERVICE, KEYPAIR_KEY)
        .map_err(|e| AppError::KeychainUnavailable(format!("entry: {e}")))?;

    match entry.get_secret() {
        Ok(bytes) => Ok(Some(bytes)),
        Err(keyring::Error::NoEntry) => Ok(None),
        Err(e) => Err(AppError::KeychainUnavailable(e.to_string())),
    }
}

fn save_to_keychain(bytes: &[u8]) -> AppResult<()> {
    let entry = Entry::new(SERVICE, KEYPAIR_KEY)
        .map_err(|e| AppError::KeychainUnavailable(format!("entry: {e}")))?;
    entry
        .set_secret(bytes)
        .map_err(|e| AppError::KeychainUnavailable(e.to_string()))?;
    Ok(())
}
